# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('bodytext', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-post_date'],
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
