# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
